common:
  user_dir: ???

generation:
  beam: 50
  max_len_a: 1.0
  max_len_b: 0
  lenpen: 1.0
  lm_weight: 0

common_eval:
  results_path: ???
  path: ???

dataset:
  max_tokens: 1000
  gen_subset: valid
  num_workers: 0

distributed_training:
  ddp_backend: c10d
  find_unused_parameters: true
  distributed_world_size: 1
  distributed_port: 29671
  nprocs_per_node: 1

override:
  noise_prob: 0.0
  noise_snr: 0
  modalities: ???
